spring.datasource.url= jdbc:postgresql://localhost:5432/telegramBot
spring.datasource.username= student
spring.datasource.password= chocolatefrog
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
telegram.bot.token=7367960447:AAECRzeY_YwAnL0zJWsXNaZyq8gS0CTv17c
