-- liquibase formatted sql

-- changeSet vkozhevatov:9
CREATE TABLE notification_tasks (
    id bigint generated by default as identity primary key ,
    chat_Id bigint not null ,
    message TEXT not null ,
    notification_date_time timestamp not null
    )

