-- liquibase formatted sql

-- changeSet vkozhevatov:1.3
CREATE TABLE notification_task (
    id bigint generated by default as identity primary key ,
    chat_Id bigint not null ,
    message TEXT not null ,
    notification_date_time timestamp not null
    )

